name: "Publish"
on:
  # Run only when pushing to main branch
  push:
    branches:
      - main
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org https://srid.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= srid.cachix.org-1:MTQ6ksbfz3LBMmjyPh0PLmos+1x+CdtJxA/J2W+PQxI=
    - uses: cachix/cachix-action@v10
      with:
        name: welteki
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build neuron site 🔧
      run: nix build
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: result/
        cname: notes.welteki.com
